import type { Metadata } from 'next'
import './globals.css'
import Navbar from '@/components/Navbar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex w-full overflow-auto justify-center ">
        <main className="w-full max-w-screen-3xl min-w-screen-md bg-primary max-h-screen-h-3xl">
          <header className="w-full h-[99px] bg-primary2">서비스이름</header>
          <section className="flex flex-row">
            <div className="flex-none w-[382px]">학원정보</div>
            <div>
              <Navbar />
              <div className="w-[1490px] h-[874px] bg-white pt-10 pl-10">
                {children}
              </div>
            </div>
          </section>
        </main>
      </body>
    </html>
  )
}
