import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className="relative w-full h-full min-w-[768px] min-h-[1024px] bg-primary-50">
        {children}
      </body>
    </html>
  )
}
